BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS loyalty_points (
   id SERIAL PRIMARY KEY,
   user_id INTEGER NOT NULL,
   accrued_point DECIMAL(10, 2) NOT NULL DEFAULT 0,
   spent_point DECIMAL(10, 2) NOT NULL DEFAULT 0,
   created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   FOREIGN KEY (user_id) REFERENCES users(id)
);

COMMIT;
