BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS orders(
   id SERIAL PRIMARY KEY,
   user_id INTEGER NOT NULL,
   number BIGINT UNIQUE NOT NULL,
   status VARCHAR (50) NULL,
   uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   FOREIGN KEY (user_id) REFERENCES users(id)
);

COMMIT;
